beef/urls.py
from django.urls import path

from . import views

app_name = "beef"
urlpatterns = [
    path('', views.lander, name='landingpage'),
]

dtree/urls.py
from django.urls import path

from . import views

app_name = "dtree"
urlpatterns = [
    path('', views.lander, name='landingpage'),
    path("newpred/", views.add_prediction, name = "newpred"),
    path("newpred/confirmed/", views.Output, name = "predictionoutput"),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views as homeviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", homeviews.home, name = "home"),
    path("purpose/", homeviews.purpose, name = "purpose"),
    path("skills/", homeviews.skills, name="skills"),
    path("datacomms/", homeviews.datacomms, name = "datacomms"),
    path("iris/", include("iris.urls")),
    path("startup1/", include("startup_success.urls")),
    path("football1/", include("football1.urls")),
    path("dtree/", include("dtree.urls")),
    path("tennis/", include("tennis.urls")),
    path("football2/", include("football2.urls")),
    path("london/", include("London.urls")),
    path("beef/", include("beef.urls")),
    path("text/", include("text.urls")),
    path("speedgun/", include("speedgun.urls")),
]

dtree/forms.py
from django import forms

class dtreeForm(forms.Form):
    Nitrogen = forms.FloatField(label='Nitrogen')
    Phosphorus = forms.FloatField(label='Phosphorus')
    Potassium = forms.FloatField(label='Potassium')
    Temperature = forms.FloatField(label='Temperature')
    Humidity = forms.FloatField(label = 'Humidity')
    pH_Value = forms.FloatField(label = 'pH_Value')
    Rainfall = forms.FloatField(label = 'Rainfall')

    def __init__(self, *args, **kwargs):
        super(dtreeForm, self).__init__(*args, **kwargs)
        self.fields['Nitrogen'].widget.attrs['placeholder'] = 39
        self.fields['Phosphorus'].widget.attrs['placeholder'] = 37
        self.fields['Potassium'].widget.attrs['placeholder'] = 25
        self.fields['pH_Value'].widget.attrs['placeholder'] = 7
        self.fields['Temperature'].widget.attrs['placeholder'] = 13.3
        self.fields['Humidity'].widget.attrs['placeholder'] = 75
        self.fields['Rainfall'].widget.attrs['placeholder'] = 72.1

main/forms.py
from django import forms

class skillnetworkForm(forms.Form):
    inputlayer = forms.IntegerField(label='Input Layer Neurons')
    hiddenlayer1 = forms.IntegerField(label='Hidden Layer 1 Neurons')
    hiddenlayer2 = forms.IntegerField(label='Hidden Layer 2 Neurons')
    outputlayer = forms.IntegerField(label='Output Layer Neurons')

    def __init__(self, *args, **kwargs):
        super(skillnetworkForm, self).__init__(*args, **kwargs)
        self.fields['inputlayer'].widget.attrs['placeholder'] = 3
        self.fields['hiddenlayer1'].widget.attrs['placeholder'] = 8
        self.fields['hiddenlayer2'].widget.attrs['placeholder'] = 7
        self.fields['outputlayer'].widget.attrs['placeholder'] = 2

dtree/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .forms import dtreeForm
import os
from django.conf import settings
from joblib import load
import numpy as np

# Create your views here.
def lander(request):
    return render(request, 'dtree/index.html')

def add_prediction(request):
    if request.method == 'POST':
        form = dtreeForm(request.POST)
        if form.is_valid():
            # Do something with data
            Nitrogen = form.cleaned_data['Nitrogen']
            Phosphorus = form.cleaned_data['Phosphorus']
            Potassium = form.cleaned_data['Potassium']
            Temperature = form.cleaned_data['Temperature']
            Humidity = form.cleaned_data['Humidity']
            pH_Value = form.cleaned_data['pH_Value']
            Rainfall = form.cleaned_data['Rainfall']
            prediction = predict(Nitrogen, Phosphorus, Potassium, Temperature, Humidity, pH_Value, Rainfall)
            return render(request, "dtree/output.html", {'result': {'Nitrogen': Nitrogen, 'Phosphorus':Phosphorus, 'Potassium': Potassium, 'Temperature':Temperature, 'Humidity': Humidity, 'pH_Value':pH_Value, 'Rainfall': Rainfall, 'Prediction': prediction}}) 
    else:
        form = dtreeForm()  # Display an empty form if the request is GET

    return render(request, 'dtree/dataentry.html', {'form': form})

def Output(request):
    return render(request, "dtree/output.html")





def predict(NI, PHO, PO, TE, HU, PH, RA):
    clf = load('dtree/treemodels/decision_tree_crops.joblib')
    PREDICTION = clf.predict(np.array([NI, PHO, PO, TE, HU, PH, RA]).reshape(1, -1))
    return PREDICTION[0]

main/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from datetime import date
from django.views import generic
from .forms import skillnetworkForm
import os
from django.conf import settings
import numpy as np

def home(request):
    return render(request, 'home.html')  # Renders the home.html template
def purpose(request):
    return render(request, 'purpose.html')
def skills(request):
    return render(request, 'skills.html')
def datacomms(request):
    return render(request, 'datacomms.html')

main/templates/dtree/dataentry.html
{% extends 'base.html' %}

{% block title %}Input data{% endblock %}

{% block content %}
<head>
    {% load static %}
    <link href="{% static 'dtree/dataentry.css' %}" rel="stylesheet">
</head>
<body>
{% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
{% endif %}
<h1>Create a New Model Prediction</h1>
<p class = "cent"> 2030 forecast: Average maximum daily temperature = 13.3 degrees, average monthly rainfall  = 72.1cm</p>
<p class = "cent"> The IQR (interquartile range) of the dataset is provided to contextualise the predictions</p>
<p class = "cent"> NPK fertiliser proportions may vary and are adapted by the farmer to achieve maximum crop yield. Experiment with different values! Units are ratios (presumably weight/volume)- not percentages.</p>
<form method="post" class="form-container">
    {% csrf_token %}
    <fieldset class="form-group">
        <div class="form-field">
            <label for="{{ form.Nitrogen.id_for_label }}">
              {{ form.Nitrogen.label }} (IQR = 21 - 84)
            </label>
            {{ form.Nitrogen }}
        </div>

        <div class="form-field">
            <label for="{{ form.Phosphorus.id_for_label }}">
                {{ form.Phosphorus.label }} (IQR = 28 - 68)
            </label>
            {{ form.Phosphorus }}
        </div>

        <div class="form-field">
            <label for="{{ form.Potassium.id_for_label }}">
                {{ form.Potassium.label }} (IQR = 20 - 49)
            </label>
            {{ form.Potassium }}
        </div>

        <div class="form-field">
            <label for="{{ form.pH_Value.id_for_label }}">
                {{ form.pH_Value.label }}   (pH must range between 0 and 14.)
            </label>
            {{ form.pH_Value }}
        </div>

        
        <div class="form-field">
            <label for="{{ form.Temperature.id_for_label }}">
                {{ form.Temperature.label }} /&#176;C (IQR = 22.8 - 28.6)
            </label>
            {{ form.Temperature }}
        </div>

        <div class="form-field">
            <label for="{{ form.Humidity.id_for_label }}">
                {{ form.Humidity.label }} %  (IQR = 60.3 - 89.9)
            </label>
            {{ form.Humidity }}
        </div>
        

        <div class="form-field">
            <label for="{{ form.Rainfall.id_for_label }}">
                {{ form.Rainfall.label }} /mm per month (IQR = 64.6 - 124.3)
            </label>
            {{ form.Rainfall }}
        </div>
    </fieldset>
    <button class="btn-submit" type="submit">Submit</button>
</form>
</body>
{% endblock %}

main/templates/dtree/output.html
<!DOCTYPE html>
<html lang="en">
<head>
{% extends 'base.html' %}
{% block title %}Confirmation{% endblock %}
{% block content %}
<h1>Output from the ML model</h1>
<p> Nitrogen: {{ result.Nitrogen }}</p>
<p>Phosphorus: {{ result.Phosphorus }}</p>
<p> Potassium: {{ result.Potassium }}</p>
<p>Temperature: {{ result.Temperature }}</p>
<p>Humidity: {{ result.Humidity }}</p>
<p>pH: {{ result.pH_Value }}</p>
<p>Rainfall {{ result.Rainfall }}</p>

<p>The recommended crop type is {{ result.Prediction }}</p>
<a href="{% url 'dtree:landingpage' %}">Back to Home</a>
<a href="{% url 'dtree:newpred' %}">Make another prediction</a>
</head>
<body style="background-color: white; color: blue;">
</body>
{% endblock %}