beef/urls.py
from django.urls import path

from . import views

app_name = "beef"
urlpatterns = [
    path('', views.lander, name='landingpage'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views as homeviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", homeviews.home, name = "home"),
    path("purpose/", homeviews.purpose, name = "purpose"),
    path("skills/", homeviews.skills, name="skills"),
    path("datacomms/", homeviews.datacomms, name = "datacomms"),
    path("iris/", include("iris.urls")),
    path("startup1/", include("startup_success.urls")),
    path("football1/", include("football1.urls")),
    path("dtree/", include("dtree.urls")),
    path("tennis/", include("tennis.urls")),
    path("football2/", include("football2.urls")),
    path("london/", include("London.urls")),
    path("beef/", include("beef.urls")),
    path("text/", include("text.urls")),
    path("speedgun/", include("speedgun.urls")),
]

startup_success/urls.py
from django.urls import path

from . import views

app_name = "startup1"
urlpatterns = [
    path('', views.lander, name='landingpage'),
    path("newpred/", views.add_prediction, name = "newpred"),
    path("newpred/confirmed/", views.Output, name = "predictionoutput"),
]

main/forms.py
from django import forms

class skillnetworkForm(forms.Form):
    inputlayer = forms.IntegerField(label='Input Layer Neurons')
    hiddenlayer1 = forms.IntegerField(label='Hidden Layer 1 Neurons')
    hiddenlayer2 = forms.IntegerField(label='Hidden Layer 2 Neurons')
    outputlayer = forms.IntegerField(label='Output Layer Neurons')

    def __init__(self, *args, **kwargs):
        super(skillnetworkForm, self).__init__(*args, **kwargs)
        self.fields['inputlayer'].widget.attrs['placeholder'] = 3
        self.fields['hiddenlayer1'].widget.attrs['placeholder'] = 8
        self.fields['hiddenlayer2'].widget.attrs['placeholder'] = 7
        self.fields['outputlayer'].widget.attrs['placeholder'] = 2

main/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from datetime import date
from django.views import generic
from .forms import skillnetworkForm
import os
from django.conf import settings
import numpy as np

def home(request):
    return render(request, 'home.html')  # Renders the home.html template
def purpose(request):
    return render(request, 'purpose.html')
def skills(request):
    return render(request, 'skills.html')
def datacomms(request):
    return render(request, 'datacomms.html')

main/templates/startup1/dataentry.html
{% extends 'base.html' %}

{% block title %}Input data{% endblock %}

{% block content %}
<head>
    {% load static %}
    <link href="{% static 'startup1/dataentry.css' %}" rel="stylesheet">
</head>
<body>
{% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
{% endif %}
<h1>Create a New Model Prediction</h1>
<form method="post" class="form-container">
    {% csrf_token %}
    <fieldset class="form-group">
        <div class="form-field">
        <label for="{{ form.funding_total_final.id_for_label }}">{{ form.funding_total_final.label }}</label>
        {{ form.funding_total_final }}
        </div>

        <div class="form-field">
            <label for="{{ form.seed.id_for_label }}">
                {{ form.seed.label }}
            </label>
            {{ form.seed }}
        </div>

        <div class="form-field">
            <label for="{{ form.roundA.id_for_label }}">
                {{ form.roundA.label }}
            </label>
            {{ form.roundA }}
        </div>

        <div class="form-field">
            <label for="{{ form.roundB.id_for_label }}">
                {{ form.roundB.label }}
            </label>
            {{ form.roundB }}
        </div>

        <div class="form-field">
            <label for="{{ form.roundC.id_for_label }}">
                {{ form.roundC.label }}
            </label>
            {{ form.roundC }}
        </div>

        <div class="form-field">
            <label for="{{ form.roundD.id_for_label }}">
                {{ form.roundD.label }}
            </label>
            {{ form.roundD }}
        </div>

        <div class="form-field">
            <label for="{{ form.roundE.id_for_label }}">
                {{ form.roundE.label }}
            </label>
            {{ form.roundE }}
        </div>

        <div class="form-field">
            <label for="{{ form.roundF.id_for_label }}">
                {{ form.roundF.label }}
            </label>
            {{ form.roundF }}
        </div>

        <div class="form-field">
            <label for="{{ form.roundG.id_for_label }}">
                {{ form.roundG.label }}
            </label>
            {{ form.roundG }}
        </div>

        <div class="form-field">
            <label for="{{ form.roundH.id_for_label }}">
                {{ form.roundH.label }}
            </label>
            {{ form.roundH }}
        </div>

        <div class="form-field">
            <label for="{{ form.yearfounded.id_for_label }}">
                {{ form.yearfounded.label }}
            </label>
            {{ form.yearfounded }}
        </div>

        <div class="form-field">
            <label for="{{ form.yearffunded.id_for_label }}">
                {{ form.yearffunded.label }}
            </label>
            {{ form.yearffunded }}
        </div>

        <div class="form-field">
            <label for="{{ form.yearlfunded.id_for_label }}">
                {{ form.yearlfunded.label }}
            </label>
            {{ form.yearlfunded }}
        </div>

       
    </fieldset>
    <fieldset class="form-group">
        <legend>Categories</legend>
        <div class="inline-checkboxes">
            <label for="{{ form.category_list_for_label }}">
                {{ form.category_list.label }}
            </label>
            <div class="checkbox-group">
                {% for checkbox in form.category_list %}
                    <div class="checkbox-item">
                        {{ checkbox }}
                    </div>
                {% endfor %}
            </div>
        </div>
    </fieldset>
    <button class="btn-submit" type="submit">Submit</button>
</form>
</body>
{% endblock %}

main/templates/startup1/output.html
<!DOCTYPE html>
<html lang="en">
<head>
{% extends 'base.html' %}
{% block title %}Confirmation{% endblock %}
{% block content %}
<h1>Output from the ML model</h1>
<p> Total Funding: {{ result.funding_total_final }}</p>
<p>Seed: {{ result.seed }}</p>
<p>Round A: {{ result.roundA }}</p>
<p>Round B: {{ result.roundB }}</p>
<p>Round C: {{ result.roundC }}</p>
<p>Round D: {{ result.roundD }}</p>
<p>Round E: {{ result.roundE }}</p>
<p>Round F: {{ result.roundF }}</p>
<p>Round G: {{ result.roundG }}</p>
<p>Round H: {{ result.roundH }}</p>

<p> Category List: {{ result.category_list }}</p>
<p>The start up status after 2022 will be: {{ result.prediction }}</p>
<a href="{% url 'startup1:landingpage' %}">Back to Home</a>
</head>
<body style="background-color: white; color: blue;">
</body>
{% endblock %}