beef/urls.py
from django.urls import path

from . import views

app_name = "beef"
urlpatterns = [
    path('', views.lander, name='landingpage'),
]

iris/urls.py
from django.urls import path

from . import views

app_name = "iris"
urlpatterns = [
    path('', views.lander, name='landingpage'),
    path("newpred/", views.add_prediction, name = "newpred"),
    path("newpred/confirmed/", views.Output, name = "predictionoutput"),
]

main/settings/templates/iris/dataentry.html
{% extends 'base.html' %}

{% block title %}Input data{% endblock %}

{% block content %}
  <h1>Create a New Model Prediction</h1>
  <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Submit</button>
  </form>
{% endblock %}

main/settings/templates/iris/index.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% block title %}Home Page{% endblock %}
{% block content %}

<body>
    <h1>Iris</h1>
    <p>Hello World </p>
    <h2>Add a New Prediction</h2>
  
    <a href="{% url 'iris:newpred' %}">
        <button type="button">Create</button>
    </a>
</body>
{% endblock %}

main/settings/templates/iris/output.html
<!DOCTYPE html>
<html lang="en">
<head>
{% extends 'base.html' %}
{% block title %}Confirmation{% endblock %}
{% block content %}
<h1>Output from the ML model</h1>
<p> Sepal Width: {{ result.sepal_width }}</p>
<p>Sepal Length {{ result.sepal_length }}</p>
<p> Sepal Width: {{ result.petal_width }}</p>
<p>Sepal Length {{ result.petal_length }}</p>
<p>The Iris type is {{ result.prediction }}</p>
<a href="{% url 'iris:landingpage' %}">Back to Home</a>
</head>
<body style="background-color: white; color: blue;">
</body>
{% endblock %}